title = "~nikdoof"
urls = ["gemini://dimension.sh/~nikdoof"]

[feeds]
"/logs/" = "~nikdoof"

[permalinks]
"/logs/" = "/logs/{{ .Date.Format `2006/01/02` }}/{{ path.Base .Permalink }}/"

[[tasks]]
input = [".gmi", ".md"]
output = ".gmi"
template = ".gmi"
static_dir = "static"
output_dir = "public"
preprocess.md = "md2gmn"
