title = "nikdoof's gemlog"
urls = ["gemini://dimension.sh/~nikdoof"]

[feeds]
"/logs/" = "nikdoof's gemlog"

[permalinks]
"/logs/" = "/logs/{{ .Date.Format `2006/01/02` }}/{{ path.Base .Permalink }}/"

[[tasks]]
input = [".gmi"]
output = ".gmi"
template = ".gmi"
static_dir = "static"
output_dir = "public"
